# Configuration for PR auto-labeling based on changed files

backend:
  - changed-files:
    - any-glob-to-any-file: 'backend/**/*'

frontend:
  - changed-files:
    - any-glob-to-any-file: 'frontend/**/*'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - '**/package.json'
      - '**/package-lock.json'

database:
  - changed-files:
    - any-glob-to-any-file:
      - 'backend/prisma/**/*'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'

ci/cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'
      - '.github/labeler.yml'

configuration:
  - changed-files:
    - any-glob-to-any-file:
      - '**/.env.example'
      - '**/tsconfig*.json'
      - '**/.eslintrc*'
      - '**/.prettierrc*'
      - '**/vite.config.*'
      - '**/tailwind.config.*'
      - '**/docker-compose.yml'
